[package]
name = "demex-node"
version = "0.1.0"
edition = "2021"

[dependencies]
open_dmx = "1.1.1"
artnet_protocol = { git = "https://github.com/matteolutz/artnet_protocol" }
clap = { version = "4.5.28", features = ["derive"] }
log = "0.4.26"
env_logger = "0.11.6"
